import { ExitRecord, HeadcountConfig } from '../types';
import { calculateTenure } from '../analytics/calculations';

interface DemoSeed {
  id: string;
  empId: string;
  name: string;
  dept: string;
  subDept: string;
  plant: string;
  empType: string;
  designation: string;
  joinDate: string;
  resignDate: string;
  lwd: string;
  exitType: string;
  reason: string;
  detailedReason: string;
  secondaryReason: string;
  noticePeriod: number;
  salaryBand: string;
  replacement: 'Yes' | 'No' | 'Pending';
  interviewDone: 'Yes' | 'No' | 'Waived';
  rehire: 'Yes' | 'No' | 'Conditional';
  remarks: string;
  gender: 'Male' | 'Female' | 'Other';
  ageGroup: 'Under 25' | '25-34' | '35-44' | '45-54' | '55+';
  grade: string;
}

const RAW_SEEDS: DemoSeed[] = [
  // 1-10 Dappar
  {
    id: 'REC-001',
    empId: 'SSW-10482',
    name: 'Harpreet Singh',
    dept: 'Production / Shop Floor',
    subDept: 'Rim Line 1',
    plant: 'Dappar (Punjab)',
    empType: 'Permanent / On-Roll',
    designation: 'Sr. Machine Operator',
    joinDate: '2021-04-12',
    resignDate: '2025-01-10',
    lwd: '2025-02-10',
    exitType: 'Voluntary Resignation',
    reason: 'Compensation & Benefits',
    detailedReason: 'Offered 32% compensation hike at an auto-ancillary forging plant in Mohali closer to home.',
    secondaryReason: 'Better Salary Elsewhere',
    noticePeriod: 30,
    salaryBand: 'Staff / Technician (Grade 2)',
    replacement: 'Yes',
    interviewDone: 'Yes',
    rehire: 'Yes',
    remarks: 'Consistent performer. Handed over all tooling logs smoothly.',
    gender: 'Male',
    ageGroup: '25-34',
    grade: 'T-2',
  },
  {
    id: 'REC-002',
    empId: 'SSW-10521',
    name: 'Jaswinder Kaur',
    dept: 'Quality Assurance',
    subDept: 'Line Inspection',
    plant: 'Dappar (Punjab)',
    empType: 'Permanent / On-Roll',
    designation: 'Quality Inspector',
    joinDate: '2022-08-01',
    resignDate: '2025-02-04',
    lwd: '2025-03-04',
    exitType: 'Voluntary Resignation',
    reason: 'Relocation',
    detailedReason: 'Relocating to Ludhiana following marriage; travel distance from Dappar unmanageable.',
    secondaryReason: 'Distance from Native Place',
    noticePeriod: 30,
    salaryBand: 'Staff / Technician (Grade 1)',
    replacement: 'Yes',
    interviewDone: 'Yes',
    rehire: 'Yes',
    remarks: 'Resignation accepted under good terms. Eligible for rehire at Ludhiana liaison center if opening arises.',
    gender: 'Female',
    ageGroup: '25-34',
    grade: 'T-1',
  },
  {
    id: 'REC-003',
    empId: 'SSW-10619',
    name: 'Baljit Verma',
    dept: 'Maintenance & Engineering',
    subDept: 'Electrical & PLC',
    plant: 'Dappar (Punjab)',
    empType: 'Permanent / On-Roll',
    designation: 'Maintenance Engineer',
    joinDate: '2020-01-15',
    resignDate: '2024-11-20',
    lwd: '2024-12-20',
    exitType: 'Voluntary Resignation',
    reason: 'Career Growth',
    detailedReason: 'Promotional stagnation; desired leadership assignment in automated robotic welding.',
    secondaryReason: 'Lack of Timely Promotion',
    noticePeriod: 30,
    salaryBand: 'Band A (Executive / Engineer)',
    replacement: 'Yes',
    interviewDone: 'Yes',
    rehire: 'Conditional',
    remarks: 'Strong technical acumen in Siemens S7 PLC.',
    gender: 'Male',
    ageGroup: '25-34',
    grade: 'E-1',
  },
  {
    id: 'REC-004',
    empId: 'SSW-10702',
    name: 'Gurdeep Singh',
    dept: 'Tool Room & Die Shop',
    subDept: 'CNC / VMC Machining',
    plant: 'Dappar (Punjab)',
    empType: 'Permanent / On-Roll',
    designation: 'VMC Programmer',
    joinDate: '2018-06-10',
    resignDate: '2024-09-15',
    lwd: '2024-10-15',
    exitType: 'Voluntary Resignation',
    reason: 'Better Industry Opportunity',
    detailedReason: 'Joined tractor manufacturing OEM in Mohali in advance tool design team.',
    secondaryReason: 'Better Salary Elsewhere',
    noticePeriod: 30,
    salaryBand: 'Band B (Sr. Engineer / Asst. Manager)',
    replacement: 'Yes',
    interviewDone: 'Yes',
    rehire: 'Yes',
    remarks: 'Extremely skilled in 5-axis machining.',
    gender: 'Male',
    ageGroup: '35-44',
    grade: 'E-2',
  },
  {
    id: 'REC-005',
    empId: 'SSW-10814',
    name: 'Simranjeet Sharma',
    dept: 'Production / Shop Floor',
    subDept: 'Disc Press Shop',
    plant: 'Dappar (Punjab)',
    empType: 'Contract / Third-Party',
    designation: 'Press Operator',
    joinDate: '2023-11-01',
    resignDate: '2024-05-12',
    lwd: '2024-05-20',
    exitType: 'Voluntary Resignation',
    reason: 'Workload / Shift',
    detailedReason: 'Consecutive night shift rotations causing severe sleep disruption and health fatigue.',
    secondaryReason: 'Unfavorable Shift Timings',
    noticePeriod: 15,
    salaryBand: 'Operator / Associate (Shop Floor)',
    replacement: 'Yes',
    interviewDone: 'No',
    rehire: 'No',
    remarks: 'Contract staff through Manpower agency.',
    gender: 'Male',
    ageGroup: 'Under 25',
    grade: 'OP-1',
  },
  {
    id: 'REC-006',
    empId: 'SSW-10890',
    name: 'Kuldeep Roy',
    dept: 'Supply Chain & Logistics',
    subDept: 'Stores & Dispatch',
    plant: 'Dappar (Punjab)',
    empType: 'Permanent / On-Roll',
    designation: 'Logistics Officer',
    joinDate: '2016-03-01',
    resignDate: '2025-01-28',
    lwd: '2025-02-28',
    exitType: 'Voluntary Resignation',
    reason: 'Personal / Family',
    detailedReason: 'Elderly father diagnosed with mobility impairment; returning to family agricultural land in Haryana.',
    secondaryReason: 'Health Issues of Family Member',
    noticePeriod: 30,
    salaryBand: 'Band A (Executive / Engineer)',
    replacement: 'Pending',
    interviewDone: 'Yes',
    rehire: 'Yes',
    remarks: 'Clean handover of SAP inventory reconciliation.',
    gender: 'Male',
    ageGroup: '35-44',
    grade: 'E-1',
  },
  {
    id: 'REC-007',
    empId: 'SSW-10943',
    name: 'Amritpal Chawla',
    dept: 'Health, Safety & Environment (HSE)',
    subDept: 'Plant Safety',
    plant: 'Dappar (Punjab)',
    empType: 'Permanent / On-Roll',
    designation: 'Safety Executive',
    joinDate: '2022-02-15',
    resignDate: '2024-08-30',
    lwd: '2024-09-30',
    exitType: 'Voluntary Resignation',
    reason: 'Higher Education',
    detailedReason: 'Secured admission in M.Tech Industrial Safety at NIT Trichy.',
    secondaryReason: 'Admitted to Higher Degree',
    noticePeriod: 30,
    salaryBand: 'Band A (Executive / Engineer)',
    replacement: 'Yes',
    interviewDone: 'Yes',
    rehire: 'Yes',
    remarks: 'High potential profile. Recommended for future lateral hiring post PG.',
    gender: 'Male',
    ageGroup: 'Under 25',
    grade: 'E-1',
  },
  {
    id: 'REC-008',
    empId: 'SSW-11005',
    name: 'Rajinder Kumar',
    dept: 'Production / Shop Floor',
    subDept: 'Assembly & Welding',
    plant: 'Dappar (Punjab)',
    empType: 'Permanent / On-Roll',
    designation: 'Lead Welder',
    joinDate: '1995-10-10',
    resignDate: '2024-12-01',
    lwd: '2024-12-31',
    exitType: 'Retirement',
    reason: 'Retirement',
    detailedReason: 'Reached normal superannuation retirement age of 58 years after 29 years of service.',
    secondaryReason: 'Unspecified / Confidential',
    noticePeriod: 30,
    salaryBand: 'Staff / Technician (Grade 2)',
    replacement: 'No',
    interviewDone: 'Yes',
    rehire: 'No',
    remarks: 'Gratuity and PF settled with honors. Commended by Plant Head.',
    gender: 'Male',
    ageGroup: '55+',
    grade: 'T-2',
  },
  {
    id: 'REC-009',
    empId: 'SSW-11120',
    name: 'Navjot Kaur',
    dept: 'Human Resources & Admin',
    subDept: 'Talent Acquisition',
    plant: 'Dappar (Punjab)',
    empType: 'Permanent / On-Roll',
    designation: 'HR Executive',
    joinDate: '2023-05-10',
    resignDate: '2024-10-05',
    lwd: '2024-11-05',
    exitType: 'Voluntary Resignation',
    reason: 'Compensation & Benefits',
    detailedReason: 'Joined tech staffing firm in Chandigarh with hybrid remote schedule and higher fixed CTC.',
    secondaryReason: 'Better Salary Elsewhere',
    noticePeriod: 30,
    salaryBand: 'Band A (Executive / Engineer)',
    replacement: 'Yes',
    interviewDone: 'Yes',
    rehire: 'Yes',
    remarks: 'Fulfilled all hiring audits before departure.',
    gender: 'Female',
    ageGroup: '25-34',
    grade: 'E-1',
  },
  {
    id: 'REC-010',
    empId: 'SSW-11233',
    name: 'Parminder Singh',
    dept: 'Production / Shop Floor',
    subDept: 'Rim Line 2',
    plant: 'Dappar (Punjab)',
    empType: 'Apprentice / Trainee',
    designation: 'Diploma Apprentice',
    joinDate: '2023-07-01',
    resignDate: '2024-06-30',
    lwd: '2024-06-30',
    exitType: 'End of Contract',
    reason: 'Contract / Temporary End',
    detailedReason: 'Completed 1-year statutory apprenticeship under NATS curriculum.',
    secondaryReason: 'Completion of Apprentice Period',
    noticePeriod: 0,
    salaryBand: 'Trainee / Apprentice',
    replacement: 'Yes',
    interviewDone: 'Waived',
    rehire: 'Yes',
    remarks: 'Certified successfully under apprenticeship act.',
    gender: 'Male',
    ageGroup: 'Under 25',
    grade: 'TR-1',
  },

  // 11-25 Jamshedpur
  {
    id: 'REC-011',
    empId: 'SSW-20104',
    name: 'Bikash Murmu',
    dept: 'Production / Shop Floor',
    subDept: 'Disc Press Shop',
    plant: 'Jamshedpur (Jharkhand)',
    empType: 'Permanent / On-Roll',
    designation: 'Press Shop Technician',
    joinDate: '2019-03-11',
    resignDate: '2025-01-15',
    lwd: '2025-02-15',
    exitType: 'Voluntary Resignation',
    reason: 'Better Industry Opportunity',
    detailedReason: 'Offered position at Tata Motors Jamshedpur Commercial Vehicle Assembly Division.',
    secondaryReason: 'Better Salary Elsewhere',
    noticePeriod: 30,
    salaryBand: 'Staff / Technician (Grade 1)',
    replacement: 'Yes',
    interviewDone: 'Yes',
    rehire: 'Yes',
    remarks: 'Strong mechanical expertise.',
    gender: 'Male',
    ageGroup: '25-34',
    grade: 'T-1',
  },
  {
    id: 'REC-012',
    empId: 'SSW-20215',
    name: 'Subhashish Das',
    dept: 'Quality Assurance',
    subDept: 'Metallurgical & Testing Lab',
    plant: 'Jamshedpur (Jharkhand)',
    empType: 'Permanent / On-Roll',
    designation: 'Plant Metallurgist',
    joinDate: '2017-09-01',
    resignDate: '2024-11-10',
    lwd: '2024-12-10',
    exitType: 'Voluntary Resignation',
    reason: 'Compensation & Benefits',
    detailedReason: 'Market adjustment for specialized metallurgical lab testing was below regional steel peers.',
    secondaryReason: 'Dissatisfaction with Annual Increment',
    noticePeriod: 30,
    salaryBand: 'Band B (Sr. Engineer / Asst. Manager)',
    replacement: 'Yes',
    interviewDone: 'Yes',
    rehire: 'Yes',
    remarks: 'Handled steel alloy certification for European export wheels.',
    gender: 'Male',
    ageGroup: '35-44',
    grade: 'E-2',
  },
  {
    id: 'REC-013',
    empId: 'SSW-20340',
    name: 'Rameshwar Soren',
    dept: 'Maintenance & Engineering',
    subDept: 'Mechanical Maintenance',
    plant: 'Jamshedpur (Jharkhand)',
    empType: 'Permanent / On-Roll',
    designation: 'Fitter / Technician',
    joinDate: '2022-01-10',
    resignDate: '2024-07-15',
    lwd: '2024-08-15',
    exitType: 'Voluntary Resignation',
    reason: 'Supervisor / Management',
    detailedReason: 'Friction with shift maintenance superintendent regarding unequal emergency call-out distribution.',
    secondaryReason: 'Strained Relationship with Shift Incharge',
    noticePeriod: 30,
    salaryBand: 'Staff / Technician (Grade 1)',
    replacement: 'Yes',
    interviewDone: 'Yes',
    rehire: 'Conditional',
    remarks: 'HR mediated; employee opted for outside offer in Adityapur.',
    gender: 'Male',
    ageGroup: '25-34',
    grade: 'T-1',
  },
  {
    id: 'REC-014',
    empId: 'SSW-20412',
    name: 'Aniruddha Sen',
    dept: 'R&D / Product Design',
    subDept: 'FEA & Simulation',
    plant: 'Jamshedpur (Jharkhand)',
    empType: 'Permanent / On-Roll',
    designation: 'CAE / Simulation Specialist',
    joinDate: '2021-10-01',
    resignDate: '2025-02-18',
    lwd: '2025-03-20',
    exitType: 'Voluntary Resignation',
    reason: 'Career Growth',
    detailedReason: 'Relocating to Bangalore for EV chassis lightweighting simulation role in OEM Tech Centre.',
    secondaryReason: 'Better Salary Elsewhere',
    noticePeriod: 30,
    salaryBand: 'Band B (Sr. Engineer / Asst. Manager)',
    replacement: 'Yes',
    interviewDone: 'Yes',
    rehire: 'Yes',
    remarks: 'High performer in Ansys dynamic wheel fatigue modeling.',
    gender: 'Male',
    ageGroup: '25-34',
    grade: 'E-2',
  },
  {
    id: 'REC-015',
    empId: 'SSW-20510',
    name: 'Pooja Pandey',
    dept: 'Finance, Accounts & Costing',
    subDept: 'Plant Costing',
    plant: 'Jamshedpur (Jharkhand)',
    empType: 'Permanent / On-Roll',
    designation: 'Cost Accountant',
    joinDate: '2023-01-15',
    resignDate: '2024-09-02',
    lwd: '2024-10-02',
    exitType: 'Voluntary Resignation',
    reason: 'Relocation',
    detailedReason: 'Relocating to Kolkata post marriage.',
    secondaryReason: 'Relocation Post-Marriage',
    noticePeriod: 30,
    salaryBand: 'Band A (Executive / Engineer)',
    replacement: 'Yes',
    interviewDone: 'Yes',
    rehire: 'Yes',
    remarks: 'SAP CO module reconciliation finished without deviation.',
    gender: 'Female',
    ageGroup: '25-34',
    grade: 'E-1',
  },
  {
    id: 'REC-016',
    empId: 'SSW-20608',
    name: 'Manoj Mahato',
    dept: 'Production / Shop Floor',
    subDept: 'Assembly & Welding',
    plant: 'Jamshedpur (Jharkhand)',
    empType: 'Contract / Third-Party',
    designation: 'MIG Welder',
    joinDate: '2023-06-15',
    resignDate: '2024-04-10',
    lwd: '2024-04-25',
    exitType: 'Voluntary Resignation',
    reason: 'Workload / Shift',
    detailedReason: 'Physical fatigue from high-temperature summer welding shifts on Line 2.',
    secondaryReason: 'Heavy Physical Workload',
    noticePeriod: 15,
    salaryBand: 'Operator / Associate (Shop Floor)',
    replacement: 'Yes',
    interviewDone: 'No',
    rehire: 'Conditional',
    remarks: 'Agency staff turnover typical during peak summer season.',
    gender: 'Male',
    ageGroup: 'Under 25',
    grade: 'OP-1',
  },
  {
    id: 'REC-017',
    empId: 'SSW-20719',
    name: 'Satyendra Prasad',
    dept: 'Tool Room & Die Shop',
    subDept: 'Die Maintenance',
    plant: 'Jamshedpur (Jharkhand)',
    empType: 'Permanent / On-Roll',
    designation: 'Sr. Die Maker',
    joinDate: '2014-04-01',
    resignDate: '2024-10-18',
    lwd: '2024-11-18',
    exitType: 'Voluntary Resignation',
    reason: 'Compensation & Benefits',
    detailedReason: 'Offered position in heavy fabrication company in Gamharia with substantially higher allowances.',
    secondaryReason: 'Better Salary Elsewhere',
    noticePeriod: 30,
    salaryBand: 'Staff / Technician (Grade 2)',
    replacement: 'Yes',
    interviewDone: 'Yes',
    rehire: 'Yes',
    remarks: 'Trained two junior die fitters before exit.',
    gender: 'Male',
    ageGroup: '35-44',
    grade: 'T-2',
  },
  {
    id: 'REC-018',
    empId: 'SSW-20831',
    name: 'Kallol Banerjee',
    dept: 'Information Technology',
    subDept: 'Plant Networking & OT',
    plant: 'Jamshedpur (Jharkhand)',
    empType: 'Permanent / On-Roll',
    designation: 'IT Systems Engineer',
    joinDate: '2021-08-16',
    resignDate: '2025-01-05',
    lwd: '2025-02-05',
    exitType: 'Voluntary Resignation',
    reason: 'Career Growth',
    detailedReason: 'Seeking transition from manufacturing OT networks into cloud infrastructure and DevOps.',
    secondaryReason: 'Better Salary Elsewhere',
    noticePeriod: 30,
    salaryBand: 'Band A (Executive / Engineer)',
    replacement: 'Yes',
    interviewDone: 'Yes',
    rehire: 'Yes',
    remarks: 'Smooth knowledge transfer of plant server backups.',
    gender: 'Male',
    ageGroup: '25-34',
    grade: 'E-1',
  },
  {
    id: 'REC-019',
    empId: 'SSW-20904',
    name: 'Sunil Kumar Hansda',
    dept: 'Production / Shop Floor',
    subDept: 'Paint Shop',
    plant: 'Jamshedpur (Jharkhand)',
    empType: 'Permanent / On-Roll',
    designation: 'Paint Shop Operator',
    joinDate: '2022-11-10',
    resignDate: '2024-06-20',
    lwd: '2024-07-20',
    exitType: 'Voluntary Resignation',
    reason: 'Health / Wellbeing',
    detailedReason: 'Respiratory sensitivity to primer solvents despite PPE; advised by physician to avoid paint booths.',
    secondaryReason: 'Health Issues of Family Member',
    noticePeriod: 30,
    salaryBand: 'Staff / Technician (Grade 1)',
    replacement: 'Yes',
    interviewDone: 'Yes',
    rehire: 'Conditional',
    remarks: 'Internal transfer to dispatch was explored but applicant chose to take rest.',
    gender: 'Male',
    ageGroup: '25-34',
    grade: 'T-1',
  },
  {
    id: 'REC-020',
    empId: 'SSW-21015',
    name: 'Pradeep Kumar Gope',
    dept: 'Supply Chain & Logistics',
    subDept: 'Raw Material Stores',
    plant: 'Jamshedpur (Jharkhand)',
    empType: 'Permanent / On-Roll',
    designation: 'Store Keeper',
    joinDate: '2019-12-01',
    resignDate: '2024-08-12',
    lwd: '2024-09-12',
    exitType: 'Voluntary Resignation',
    reason: 'Personal / Family',
    detailedReason: 'Starting own transportation dealership business with brothers in Chaibasa.',
    secondaryReason: 'Personal Business / Self-Employment',
    noticePeriod: 30,
    salaryBand: 'Staff / Technician (Grade 1)',
    replacement: 'Yes',
    interviewDone: 'Yes',
    rehire: 'Yes',
    remarks: 'All coil stock verification completed without deficit.',
    gender: 'Male',
    ageGroup: '25-34',
    grade: 'T-1',
  },

  // 21-35 Chennai
  {
    id: 'REC-021',
    empId: 'SSW-30118',
    name: 'Karthik Subramanian',
    dept: 'Production / Shop Floor',
    subDept: 'Rim Line 1',
    plant: 'Chennai (Tamil Nadu)',
    empType: 'Permanent / On-Roll',
    designation: 'Shift Supervisor',
    joinDate: '2018-05-15',
    resignDate: '2025-01-12',
    lwd: '2025-02-12',
    exitType: 'Voluntary Resignation',
    reason: 'Better Industry Opportunity',
    detailedReason: 'Joined Hyundai OEM vendor park in Sriperumbudur with higher managerial grade.',
    secondaryReason: 'Better Salary Elsewhere',
    noticePeriod: 30,
    salaryBand: 'Band B (Sr. Engineer / Asst. Manager)',
    replacement: 'Yes',
    interviewDone: 'Yes',
    rehire: 'Yes',
    remarks: 'Key contributor to OEE ramp-up on Rim Line 1.',
    gender: 'Male',
    ageGroup: '35-44',
    grade: 'E-2',
  },
  {
    id: 'REC-022',
    empId: 'SSW-30230',
    name: 'Senthil Kumar V',
    dept: 'Quality Assurance',
    subDept: 'Final Audit & PDI',
    plant: 'Chennai (Tamil Nadu)',
    empType: 'Permanent / On-Roll',
    designation: 'Sr. Quality Engineer',
    joinDate: '2019-11-20',
    resignDate: '2024-10-15',
    lwd: '2024-11-15',
    exitType: 'Voluntary Resignation',
    reason: 'Compensation & Benefits',
    detailedReason: 'Compensation out of sync with Korean automotive suppliers in Oragadam corridor.',
    secondaryReason: 'Better Salary Elsewhere',
    noticePeriod: 30,
    salaryBand: 'Band B (Sr. Engineer / Asst. Manager)',
    replacement: 'Yes',
    interviewDone: 'Yes',
    rehire: 'Yes',
    remarks: 'Auditor for customer quality complaints; zero open non-conformances left.',
    gender: 'Male',
    ageGroup: '35-44',
    grade: 'E-2',
  },
  {
    id: 'REC-023',
    empId: 'SSW-30345',
    name: 'Anitha Rajendran',
    dept: 'Human Resources & Admin',
    subDept: 'Time Office & Payroll',
    plant: 'Chennai (Tamil Nadu)',
    empType: 'Permanent / On-Roll',
    designation: 'HR Executive',
    joinDate: '2022-04-01',
    resignDate: '2024-07-22',
    lwd: '2024-08-22',
    exitType: 'Voluntary Resignation',
    reason: 'Relocation',
    detailedReason: 'Relocating to Coimbatore due to spouse software transfer.',
    secondaryReason: 'Distance from Native Place',
    noticePeriod: 30,
    salaryBand: 'Band A (Executive / Engineer)',
    replacement: 'Yes',
    interviewDone: 'Yes',
    rehire: 'Yes',
    remarks: 'Processed all statutory PF/ESI filings punctually.',
    gender: 'Female',
    ageGroup: '25-34',
    grade: 'E-1',
  },
  {
    id: 'REC-024',
    empId: 'SSW-30460',
    name: 'Muruganandham P',
    dept: 'Maintenance & Engineering',
    subDept: 'Hydraulics & Pneumatics',
    plant: 'Chennai (Tamil Nadu)',
    empType: 'Permanent / On-Roll',
    designation: 'Hydraulic Specialist',
    joinDate: '2016-08-01',
    resignDate: '2024-11-30',
    lwd: '2024-12-31',
    exitType: 'Voluntary Resignation',
    reason: 'Career Growth',
    detailedReason: 'Aspired to transition into automation systems engineering; limited vacancy in plant.',
    secondaryReason: 'Lack of Timely Promotion',
    noticePeriod: 30,
    salaryBand: 'Band A (Executive / Engineer)',
    replacement: 'Yes',
    interviewDone: 'Yes',
    rehire: 'Yes',
    remarks: 'Handled hydraulic presses preventive maintenance impeccably.',
    gender: 'Male',
    ageGroup: '35-44',
    grade: 'E-1',
  },
  {
    id: 'REC-025',
    empId: 'SSW-30571',
    name: 'Dinesh Balaji',
    dept: 'Production / Shop Floor',
    subDept: 'Disc Press Shop',
    plant: 'Chennai (Tamil Nadu)',
    empType: 'Permanent / On-Roll',
    designation: 'Press Machine Operator',
    joinDate: '2023-03-10',
    resignDate: '2024-05-18',
    lwd: '2024-06-18',
    exitType: 'Voluntary Resignation',
    reason: 'Workload / Shift',
    detailedReason: 'Long commute from Tiruvallur combined with 6-day 12-hour overtime shifts during export surge.',
    secondaryReason: 'Commute / Transportation Challenges',
    noticePeriod: 30,
    salaryBand: 'Staff / Technician (Grade 1)',
    replacement: 'Yes',
    interviewDone: 'Yes',
    rehire: 'Conditional',
    remarks: 'Exit interview flagged transportation route bottleneck.',
    gender: 'Male',
    ageGroup: '25-34',
    grade: 'T-1',
  },
  {
    id: 'REC-026',
    empId: 'SSW-30689',
    name: 'Vigneshwaran K',
    dept: 'Tool Room & Die Shop',
    subDept: 'Die Maintenance',
    plant: 'Chennai (Tamil Nadu)',
    empType: 'Apprentice / Trainee',
    designation: 'Tool & Die Trainee',
    joinDate: '2023-09-01',
    resignDate: '2024-08-31',
    lwd: '2024-08-31',
    exitType: 'End of Contract',
    reason: 'Contract / Temporary End',
    detailedReason: '1-year apprentice tenure ended; decided to enroll in full-time BE Mechanical.',
    secondaryReason: 'Completion of Apprentice Period',
    noticePeriod: 0,
    salaryBand: 'Trainee / Apprentice',
    replacement: 'Yes',
    interviewDone: 'Waived',
    rehire: 'Yes',
    remarks: 'Good diligence in die polishing and bench fitting.',
    gender: 'Male',
    ageGroup: 'Under 25',
    grade: 'TR-1',
  },
  {
    id: 'REC-027',
    empId: 'SSW-30792',
    name: 'Saravanan M',
    dept: 'Production / Shop Floor',
    subDept: 'Paint Shop',
    plant: 'Chennai (Tamil Nadu)',
    empType: 'Contract / Third-Party',
    designation: 'ED Coater',
    joinDate: '2023-10-15',
    resignDate: '2024-03-25',
    lwd: '2024-04-05',
    exitType: 'Voluntary Resignation',
    reason: 'Work Environment',
    detailedReason: 'High ambient humidity and fumes in cathodic electrodeposition prep tank area.',
    secondaryReason: 'Heavy Physical Workload',
    noticePeriod: 15,
    salaryBand: 'Operator / Associate (Shop Floor)',
    replacement: 'Yes',
    interviewDone: 'No',
    rehire: 'No',
    remarks: 'Third-party contractor replacement deployed.',
    gender: 'Male',
    ageGroup: 'Under 25',
    grade: 'OP-1',
  },
  {
    id: 'REC-028',
    empId: 'SSW-30855',
    name: 'Gowtham N',
    dept: 'Quality Assurance',
    subDept: 'QMS & Audits',
    plant: 'Chennai (Tamil Nadu)',
    empType: 'Permanent / On-Roll',
    designation: 'IATF Audit Lead',
    joinDate: '2019-01-10',
    resignDate: '2024-12-08',
    lwd: '2025-01-08',
    exitType: 'Voluntary Resignation',
    reason: 'Career Growth',
    detailedReason: 'Offered Corporate Quality Manager role in tier-1 auto supplier headquarters.',
    secondaryReason: 'Better Salary Elsewhere',
    noticePeriod: 30,
    salaryBand: 'Band C (Manager / Sr. Manager)',
    replacement: 'Yes',
    interviewDone: 'Yes',
    rehire: 'Yes',
    remarks: 'Instrumental in IATF 16949 recertification.',
    gender: 'Male',
    ageGroup: '35-44',
    grade: 'M-1',
  },

  // 29-45 Mehsana & Saraikela & Extended Records
  {
    id: 'REC-029',
    empId: 'SSW-40102',
    name: 'Chirag Patel',
    dept: 'Production / Shop Floor',
    subDept: 'Rim Line 1',
    plant: 'Mehsana (Gujarat)',
    empType: 'Permanent / On-Roll',
    designation: 'Line In-Charge',
    joinDate: '2019-06-15',
    resignDate: '2025-01-20',
    lwd: '2025-02-20',
    exitType: 'Voluntary Resignation',
    reason: 'Compensation & Benefits',
    detailedReason: 'Higher incentive package at Sanand automotive cluster.',
    secondaryReason: 'Better Salary Elsewhere',
    noticePeriod: 30,
    salaryBand: 'Band B (Sr. Engineer / Asst. Manager)',
    replacement: 'Yes',
    interviewDone: 'Yes',
    rehire: 'Yes',
    remarks: 'Consistent delivery on rim rolling targets.',
    gender: 'Male',
    ageGroup: '35-44',
    grade: 'E-2',
  },
  {
    id: 'REC-030',
    empId: 'SSW-40224',
    name: 'Bhavesh Prajapati',
    dept: 'Maintenance & Engineering',
    subDept: 'Utility & Power House',
    plant: 'Mehsana (Gujarat)',
    empType: 'Permanent / On-Roll',
    designation: 'Boiler / Utility Operator',
    joinDate: '2017-02-10',
    resignDate: '2024-10-30',
    lwd: '2024-11-30',
    exitType: 'Voluntary Resignation',
    reason: 'Personal / Family',
    detailedReason: 'Taking over father agricultural farm equipment workshop in Patan.',
    secondaryReason: 'Personal Business / Self-Employment',
    noticePeriod: 30,
    salaryBand: 'Staff / Technician (Grade 1)',
    replacement: 'Yes',
    interviewDone: 'Yes',
    rehire: 'Yes',
    remarks: 'First class boiler attendant certificate returned.',
    gender: 'Male',
    ageGroup: '35-44',
    grade: 'T-1',
  },
  {
    id: 'REC-031',
    empId: 'SSW-40331',
    name: 'Mehul Joshi',
    dept: 'Supply Chain & Logistics',
    subDept: 'Raw Material Stores',
    plant: 'Mehsana (Gujarat)',
    empType: 'Permanent / On-Roll',
    designation: 'Procurement Officer',
    joinDate: '2022-09-01',
    resignDate: '2024-06-15',
    lwd: '2024-07-15',
    exitType: 'Voluntary Resignation',
    reason: 'Supervisor / Management',
    detailedReason: 'Differences with materials manager over vendor dispute resolution and freight approvals.',
    secondaryReason: 'Strained Relationship with Shift Incharge',
    noticePeriod: 30,
    salaryBand: 'Band A (Executive / Engineer)',
    replacement: 'Yes',
    interviewDone: 'Yes',
    rehire: 'Conditional',
    remarks: 'Settled vendor advance accounts smoothly.',
    gender: 'Male',
    ageGroup: '25-34',
    grade: 'E-1',
  },
  {
    id: 'REC-032',
    empId: 'SSW-40455',
    name: 'Dhaval Shah',
    dept: 'Quality Assurance',
    subDept: 'Incoming QC',
    plant: 'Mehsana (Gujarat)',
    empType: 'Permanent / On-Roll',
    designation: 'Incoming Inspection Engineer',
    joinDate: '2020-11-15',
    resignDate: '2024-12-15',
    lwd: '2025-01-15',
    exitType: 'Voluntary Resignation',
    reason: 'Career Growth',
    detailedReason: 'Selected for Gujarat State Public Service Commission technical wing.',
    secondaryReason: 'Better Salary Elsewhere',
    noticePeriod: 30,
    salaryBand: 'Band A (Executive / Engineer)',
    replacement: 'Yes',
    interviewDone: 'Yes',
    rehire: 'Yes',
    remarks: 'Exited on good terms for government service.',
    gender: 'Male',
    ageGroup: '25-34',
    grade: 'E-1',
  },
  {
    id: 'REC-033',
    empId: 'SSW-50112',
    name: 'Sanat Mahato',
    dept: 'Production / Shop Floor',
    subDept: 'Assembly & Welding',
    plant: 'Saraikela (Jharkhand)',
    empType: 'Permanent / On-Roll',
    designation: 'Sub-Arc Welder',
    joinDate: '2018-04-10',
    resignDate: '2025-02-01',
    lwd: '2025-03-01',
    exitType: 'Voluntary Resignation',
    reason: 'Compensation & Benefits',
    detailedReason: 'Offered higher grade in heavy engineering plant in Gamharia.',
    secondaryReason: 'Better Salary Elsewhere',
    noticePeriod: 30,
    salaryBand: 'Staff / Technician (Grade 2)',
    replacement: 'Yes',
    interviewDone: 'Yes',
    rehire: 'Yes',
    remarks: 'Proficient in automatic wheel circum welding.',
    gender: 'Male',
    ageGroup: '25-34',
    grade: 'T-2',
  },
  {
    id: 'REC-034',
    empId: 'SSW-50225',
    name: 'Prabhat Kumar Singh',
    dept: 'Tool Room & Die Shop',
    subDept: 'Die Maintenance',
    plant: 'Saraikela (Jharkhand)',
    empType: 'Permanent / On-Roll',
    designation: 'Die Setter',
    joinDate: '2021-02-01',
    resignDate: '2024-08-20',
    lwd: '2024-09-20',
    exitType: 'Voluntary Resignation',
    reason: 'Workload / Shift',
    detailedReason: 'Excessive overtime during wheel export delivery deadlines.',
    secondaryReason: 'Heavy Physical Workload',
    noticePeriod: 30,
    salaryBand: 'Staff / Technician (Grade 1)',
    replacement: 'Yes',
    interviewDone: 'Yes',
    rehire: 'Conditional',
    remarks: 'Complained of back strain during die changeovers.',
    gender: 'Male',
    ageGroup: '25-34',
    grade: 'T-1',
  },
  {
    id: 'REC-035',
    empId: 'SSW-50340',
    name: 'Debjani Mukherjee',
    dept: 'Human Resources & Admin',
    subDept: 'Employee Relations & IR',
    plant: 'Saraikela (Jharkhand)',
    empType: 'Permanent / On-Roll',
    designation: 'IR Specialist',
    joinDate: '2020-07-01',
    resignDate: '2024-11-05',
    lwd: '2024-12-05',
    exitType: 'Voluntary Resignation',
    reason: 'Relocation',
    detailedReason: 'Moving to Kolkata due to marriage.',
    secondaryReason: 'Relocation Post-Marriage',
    noticePeriod: 30,
    salaryBand: 'Band B (Sr. Engineer / Asst. Manager)',
    replacement: 'Yes',
    interviewDone: 'Yes',
    rehire: 'Yes',
    remarks: 'Effectively managed union bi-monthly meetings.',
    gender: 'Female',
    ageGroup: '25-34',
    grade: 'E-2',
  },
  {
    id: 'REC-036',
    empId: 'SSW-50456',
    name: 'Ashok Karmakar',
    dept: 'Maintenance & Engineering',
    subDept: 'Mechanical Maintenance',
    plant: 'Saraikela (Jharkhand)',
    empType: 'Permanent / On-Roll',
    designation: 'Hydraulic Fitter',
    joinDate: '2015-09-10',
    resignDate: '2024-05-30',
    lwd: '2024-06-30',
    exitType: 'Involuntary Termination',
    reason: 'Attendance / Conduct',
    detailedReason: 'Repeated unauthorized absenteeism and failure to respond to statutory show-cause notices.',
    secondaryReason: 'Disciplinary Action',
    noticePeriod: 0,
    salaryBand: 'Staff / Technician (Grade 1)',
    replacement: 'Yes',
    interviewDone: 'No',
    rehire: 'No',
    remarks: 'Inquiry officer report submitted. Exited following formal domestic inquiry.',
    gender: 'Male',
    ageGroup: '35-44',
    grade: 'T-1',
  },
  {
    id: 'REC-037',
    empId: 'SSW-10339',
    name: 'Gurpreet Singh Gill',
    dept: 'Production / Shop Floor',
    subDept: 'Rim Line 1',
    plant: 'Dappar (Punjab)',
    empType: 'Permanent / On-Roll',
    designation: 'Production Engineer',
    joinDate: '2023-01-10',
    resignDate: '2024-04-15',
    lwd: '2024-05-15',
    exitType: 'Voluntary Resignation',
    reason: 'Higher Education',
    detailedReason: 'Selected for MBA in Operations at IIM Amritsar.',
    secondaryReason: 'Admitted to Higher Degree',
    noticePeriod: 30,
    salaryBand: 'Band A (Executive / Engineer)',
    replacement: 'Yes',
    interviewDone: 'Yes',
    rehire: 'Yes',
    remarks: 'High potential GET; completed handover.',
    gender: 'Male',
    ageGroup: 'Under 25',
    grade: 'E-1',
  },
  {
    id: 'REC-038',
    empId: 'SSW-30910',
    name: 'Sridhar Narayanan',
    dept: 'R&D / Product Design',
    subDept: 'Wheel Design',
    plant: 'Chennai (Tamil Nadu)',
    empType: 'Permanent / On-Roll',
    designation: 'CAD Design Engineer',
    joinDate: '2022-06-01',
    resignDate: '2025-02-14',
    lwd: '2025-03-14',
    exitType: 'Voluntary Resignation',
    reason: 'Compensation & Benefits',
    detailedReason: 'Salary review did not match market rates for Catia V5 specialized alloy wheel designers.',
    secondaryReason: 'Dissatisfaction with Annual Increment',
    noticePeriod: 30,
    salaryBand: 'Band A (Executive / Engineer)',
    replacement: 'Yes',
    interviewDone: 'Yes',
    rehire: 'Yes',
    remarks: 'Export wheel designs archived in PDM vault.',
    gender: 'Male',
    ageGroup: '25-34',
    grade: 'E-1',
  },
  {
    id: 'REC-039',
    empId: 'SSW-21102',
    name: 'Sanjay Hembram',
    dept: 'Production / Shop Floor',
    subDept: 'Disc Press Shop',
    plant: 'Jamshedpur (Jharkhand)',
    empType: 'Permanent / On-Roll',
    designation: 'Senior Press Operator',
    joinDate: '2016-11-20',
    resignDate: '2024-07-28',
    lwd: '2024-08-28',
    exitType: 'Voluntary Resignation',
    reason: 'Work Environment',
    detailedReason: 'Excessive heat and noise in heavy blanking press bay.',
    secondaryReason: 'Heavy Physical Workload',
    noticePeriod: 30,
    salaryBand: 'Staff / Technician (Grade 2)',
    replacement: 'Yes',
    interviewDone: 'Yes',
    rehire: 'Conditional',
    remarks: 'Long tenured operator; requested lighter duty earlier.',
    gender: 'Male',
    ageGroup: '35-44',
    grade: 'T-2',
  },
  {
    id: 'REC-040',
    empId: 'SSW-40588',
    name: 'Priyank Vaghela',
    dept: 'Health, Safety & Environment (HSE)',
    subDept: 'Environmental Compliance',
    plant: 'Mehsana (Gujarat)',
    empType: 'Permanent / On-Roll',
    designation: 'ETP Incharge',
    joinDate: '2021-05-15',
    resignDate: '2024-09-18',
    lwd: '2024-10-18',
    exitType: 'Voluntary Resignation',
    reason: 'Career Growth',
    detailedReason: 'Offered Corporate ESG Lead position at chemical MNC in Dahej.',
    secondaryReason: 'Better Salary Elsewhere',
    noticePeriod: 30,
    salaryBand: 'Band B (Sr. Engineer / Asst. Manager)',
    replacement: 'Yes',
    interviewDone: 'Yes',
    rehire: 'Yes',
    remarks: 'GPCB compliance documents audited cleanly.',
    gender: 'Male',
    ageGroup: '25-34',
    grade: 'E-2',
  },
];

// Helper to expand seed records across realistic time-series and plants to produce 110 rich records
function generateFullDemoDataset(): ExitRecord[] {
  const result: ExitRecord[] = [];

  // Add all primary hand-crafted seeds
  RAW_SEEDS.forEach((seed) => {
    const { tenureMonths, tenureYears, tenureBucket } = calculateTenure(
      seed.joinDate,
      seed.lwd,
      seed.resignDate
    );

    result.push({
      id: seed.id,
      employeeId: seed.empId,
      employeeName: seed.name,
      department: seed.dept,
      subDepartment: seed.subDept,
      plant: seed.plant,
      employmentType: seed.empType,
      designation: seed.designation,
      joiningDate: seed.joinDate,
      resignationDate: seed.resignDate,
      lastWorkingDate: seed.lwd,
      exitType: seed.exitType,
      primaryReason: seed.reason,
      detailedReason: seed.detailedReason,
      secondaryReason: seed.secondaryReason,
      noticePeriod: seed.noticePeriod,
      salaryBand: seed.salaryBand,
      replacementRequired: seed.replacement,
      exitInterviewCompleted: seed.interviewDone,
      rehireEligible: seed.rehire,
      hrRemarks: seed.remarks,
      dataEntryDate: seed.resignDate,
      gender: seed.gender,
      ageGroup: seed.ageGroup,
      grade: seed.grade,
      tenureMonths,
      tenureYears,
      tenureBucket,
    });
  });

  // Procedurally generate additional realistic records across 2024-2025 to achieve statistical depth
  const plants = [
    'Dappar (Punjab)',
    'Jamshedpur (Jharkhand)',
    'Chennai (Tamil Nadu)',
    'Mehsana (Gujarat)',
    'Saraikela (Jharkhand)',
  ];

  const depts = [
    { dept: 'Production / Shop Floor', sub: 'Rim Line 1', desig: 'CNC Operator', band: 'Staff / Technician (Grade 1)', grade: 'T-1' },
    { dept: 'Production / Shop Floor', sub: 'Disc Press Shop', desig: 'Press Operator', band: 'Operator / Associate (Shop Floor)', grade: 'OP-1' },
    { dept: 'Production / Shop Floor', sub: 'Assembly & Welding', desig: 'Robotic Welding Tech', band: 'Staff / Technician (Grade 2)', grade: 'T-2' },
    { dept: 'Quality Assurance', sub: 'Incoming QC', desig: 'Inspection Engineer', band: 'Band A (Executive / Engineer)', grade: 'E-1' },
    { dept: 'Quality Assurance', sub: 'Line Inspection', desig: 'Quality Supervisor', band: 'Band B (Sr. Engineer / Asst. Manager)', grade: 'E-2' },
    { dept: 'Maintenance & Engineering', sub: 'Mechanical Maintenance', desig: 'Maintenance Tech', band: 'Staff / Technician (Grade 1)', grade: 'T-1' },
    { dept: 'Maintenance & Engineering', sub: 'Electrical & PLC', desig: 'Electrical Engineer', band: 'Band A (Executive / Engineer)', grade: 'E-1' },
    { dept: 'Tool Room & Die Shop', sub: 'Die Maintenance', desig: 'Die Polisher', band: 'Staff / Technician (Grade 1)', grade: 'T-1' },
    { dept: 'Supply Chain & Logistics', sub: 'Dispatch & Shipping', desig: 'Logistics Supervisor', band: 'Band A (Executive / Engineer)', grade: 'E-1' },
    { dept: 'Human Resources & Admin', sub: 'Talent Acquisition', desig: 'HR Executive', band: 'Band A (Executive / Engineer)', grade: 'E-1' },
  ];

  const reasons = [
    { reason: 'Compensation & Benefits', sec: 'Better Salary Elsewhere', text: 'Secured higher package at competing component supplier.' },
    { reason: 'Career Growth', sec: 'Lack of Timely Promotion', text: 'Seeking leadership role with expanded line oversight.' },
    { reason: 'Workload / Shift', sec: 'Unfavorable Shift Timings', text: 'Fatigue from continuous rotating 3-shift pattern.' },
    { reason: 'Relocation', sec: 'Distance from Native Place', text: 'Relocating closer to hometown due to domestic responsibilities.' },
    { reason: 'Personal / Family', sec: 'Family Commitments', text: 'Family eldercare obligations requiring relocation.' },
    { reason: 'Better Industry Opportunity', sec: 'Better Salary Elsewhere', text: 'Recruited by commercial vehicle OEM assembly plant.' },
    { reason: 'Higher Education', sec: 'Admitted to Higher Degree', text: 'Enrolled in master degree program.' },
    { reason: 'Work Environment', sec: 'Heavy Physical Workload', text: 'Physical strain in high temperature press operations.' },
    { reason: 'Supervisor / Management', sec: 'Conflict with Supervisor', text: 'Interpersonal friction with department shift manager.' },
    { reason: 'Health / Wellbeing', sec: 'Health Issues of Family Member', text: 'Medical condition necessitating reduced stress profile.' },
  ];

  const firstNames = ['Amit', 'Rajesh', 'Suresh', 'Manish', 'Deepak', 'Vijay', 'Prakash', 'Sanjay', 'Sunil', 'Anil', 'Ravi', 'Girish', 'Satish', 'Tarun', 'Naveen', 'Arun', 'Pankaj', 'Vikas', 'Gaurav', 'Nitin', 'Rohan', 'Ashish', 'Sachin', 'Mohit', 'Dinesh', 'Ajay', 'Chetan', 'Sumit', 'Vinod', 'Hemant'];
  const lastNames = ['Sharma', 'Verma', 'Singh', 'Patel', 'Kumar', 'Yadav', 'Gupta', 'Mishra', 'Pandey', 'Chauhan', 'Thakur', 'Rathore', 'Nair', 'Pillai', 'Reddy', 'Rao', 'Das', 'Roy', 'Sengupta', 'Chakraborty', 'Gope', 'Mahato', 'Hansda', 'Soren', 'Bose', 'Murmu', 'Biswas', 'Pal', 'Dey', 'Sen'];

  let count = RAW_SEEDS.length + 1;

  // Generate 75 additional records distributed across 2024 and 2025
  for (let y = 2024; y <= 2025; y++) {
    for (let m = 1; m <= 12; m++) {
      // 3 records per month on average
      const recordsThisMonth = m === 4 || m === 5 || m === 10 ? 4 : 3; // Post appraisal spikes
      for (let r = 0; r < recordsThisMonth; r++) {
        if (count > 115) break;

        const plant = plants[(count + r) % plants.length];
        const deptObj = depts[(count + m + r) % depts.length];
        const reasonObj = reasons[(count * 3 + r) % reasons.length];
        const fName = firstNames[(count + r) % firstNames.length];
        const lName = lastNames[(count * 2 + m) % lastNames.length];

        // Random joining date between 1 and 7 years prior
        const tenureYearsRandom = (0.3 + ((count * 7 + r * 11) % 65) / 10);
        const exitDay = Math.min(28, 5 + ((count * 3 + r * 7) % 22));
        const exitMonthStr = String(m).padStart(2, '0');
        const exitDayStr = String(exitDay).padStart(2, '0');
        const exitDate = `${y}-${exitMonthStr}-${exitDayStr}`;

        const exitDateObj = new Date(exitDate);
        const joinDateObj = new Date(exitDateObj.getTime() - tenureYearsRandom * 365.25 * 24 * 3600 * 1000);
        const joinYear = joinDateObj.getFullYear();
        const joinMonthStr = String(joinDateObj.getMonth() + 1).padStart(2, '0');
        const joinDayStr = String(Math.min(28, joinDateObj.getDate())).padStart(2, '0');
        const joinDate = `${joinYear}-${joinMonthStr}-${joinDayStr}`;

        const lwdObj = new Date(exitDateObj.getTime() + 30 * 24 * 3600 * 1000);
        const lwdStr = `${lwdObj.getFullYear()}-${String(lwdObj.getMonth() + 1).padStart(2, '0')}-${String(Math.min(28, lwdObj.getDate())).padStart(2, '0')}`;

        const isVol = count % 11 !== 0;
        const exitType = isVol
          ? 'Voluntary Resignation'
          : count % 22 === 0
          ? 'End of Contract'
          : count % 33 === 0
          ? 'Involuntary Termination'
          : 'Retirement';

        const { tenureMonths, tenureYears, tenureBucket } = calculateTenure(joinDate, lwdStr, exitDate);

        const ageBucket: 'Under 25' | '25-34' | '35-44' | '45-54' | '55+' =
          tenureYears > 10 ? '45-54' : tenureYears > 4 ? '35-44' : tenureYears < 1 ? 'Under 25' : '25-34';

        result.push({
          id: `REC-${String(count).padStart(3, '0')}`,
          employeeId: `SSW-${10000 + count * 17}`,
          employeeName: `${fName} ${lName}`,
          department: deptObj.dept,
          subDepartment: deptObj.sub,
          plant,
          employmentType: count % 8 === 0 ? 'Contract / Third-Party' : 'Permanent / On-Roll',
          designation: deptObj.desig,
          joiningDate: joinDate,
          resignationDate: exitDate,
          lastWorkingDate: lwdStr,
          exitType,
          primaryReason: exitType === 'Retirement' ? 'Retirement' : reasonObj.reason,
          detailedReason: reasonObj.text,
          secondaryReason: reasonObj.sec,
          noticePeriod: 30,
          salaryBand: deptObj.band,
          replacementRequired: count % 3 === 0 ? 'Yes' : 'Pending',
          exitInterviewCompleted: count % 7 === 0 ? 'No' : 'Yes',
          rehireEligible: exitType === 'Involuntary Termination' ? 'No' : 'Yes',
          hrRemarks: 'Handover documented according to standard HR operating procedure.',
          dataEntryDate: exitDate,
          gender: count % 6 === 0 ? 'Female' : 'Male',
          ageGroup: ageBucket,
          grade: deptObj.grade,
          tenureMonths,
          tenureYears,
          tenureBucket,
        });

        count++;
      }
    }
  }

  return result;
}

export const DEMO_EXIT_RECORDS: ExitRecord[] = generateFullDemoDataset();

export const DEMO_HEADCOUNTS: HeadcountConfig[] = [
  { plant: 'Dappar (Punjab)', department: 'All', year: 2024, month: 1, headcount: 1450 },
  { plant: 'Jamshedpur (Jharkhand)', department: 'All', year: 2024, month: 1, headcount: 1820 },
  { plant: 'Chennai (Tamil Nadu)', department: 'All', year: 2024, month: 1, headcount: 1280 },
  { plant: 'Mehsana (Gujarat)', department: 'All', year: 2024, month: 1, headcount: 950 },
  { plant: 'Saraikela (Jharkhand)', department: 'All', year: 2024, month: 1, headcount: 620 },
  { plant: 'Dappar (Punjab)', department: 'All', year: 2025, month: 1, headcount: 1480 },
  { plant: 'Jamshedpur (Jharkhand)', department: 'All', year: 2025, month: 1, headcount: 1860 },
  { plant: 'Chennai (Tamil Nadu)', department: 'All', year: 2025, month: 1, headcount: 1310 },
  { plant: 'Mehsana (Gujarat)', department: 'All', year: 2025, month: 1, headcount: 980 },
  { plant: 'Saraikela (Jharkhand)', department: 'All', year: 2025, month: 1, headcount: 640 },
];
